apiVersion: v1
kind: Service
metadata:
  name: landmark-app-lb
  namespace: landmark
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0a2d31396b0ea54c1, subnet-0243e0e069d865f3c"
spec:
  type: LoadBalancer
  selector:
    app: landmark-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
